FROM python:latest

RUN apt-get update && apt-get install -y curl jq

RUN pip install poetry uvicorn

WORKDIR /app

COPY . .

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN poetry install

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]
